# Generated by Django 4.2.4 on 2023-09-19 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("phone", models.BigIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("a", "By Air"), ("e", "by Earth")],
                        default="e",
                        max_length=1,
                    ),
                ),
                ("customer_name", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=13)),
                ("passport_number", models.BigIntegerField()),
                ("real_price", models.IntegerField(default=1600)),
                ("price", models.IntegerField()),
                ("spended", models.IntegerField()),
                (
                    "description",
                    models.CharField(default=None, max_length=800, null=True),
                ),
                ("from_city", models.CharField(default="", max_length=200, null=True)),
                ("to_city", models.CharField(default="", max_length=200, null=True)),
                ("do_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("value", models.IntegerField()),
                ("is_income", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(default=None, max_length=300, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=13)),
                ("passport_number", models.BigIntegerField()),
                (
                    "visa_term",
                    models.CharField(
                        choices=[
                            ("2", "Two month"),
                            ("3", "Three month"),
                            ("4", "45 days"),
                        ],
                        default="2",
                        max_length=1,
                    ),
                ),
                ("real_price", models.IntegerField(default=1600)),
                ("price", models.IntegerField()),
                ("spended", models.IntegerField()),
                (
                    "description",
                    models.CharField(default=None, max_length=800, null=True),
                ),
                ("city", models.CharField(default="", max_length=200, null=True)),
                ("do_date", models.DateField()),
                ("done", models.BooleanField(default=False)),
                (
                    "functor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visas",
                        to="agency.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Renew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=13)),
                ("passport_number", models.BigIntegerField()),
                (
                    "renew_type",
                    models.CharField(
                        choices=[("e", "Exit"), ("r", "Renew")],
                        default="2",
                        max_length=1,
                    ),
                ),
                ("real_price", models.IntegerField(default=1600)),
                ("price", models.IntegerField()),
                ("spended", models.IntegerField()),
                (
                    "description",
                    models.CharField(default=None, max_length=800, null=True),
                ),
                ("city", models.CharField(default="", max_length=200, null=True)),
                ("do_date", models.DateField()),
                (
                    "functor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renews",
                        to="agency.company",
                    ),
                ),
            ],
        ),
    ]
